language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '4'
  - '6'
before_script:
  - npm prune
script:
  - ./next-update-travis.sh
  - npm test
  - npm run postinstall -- --force
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
